sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_7ab094ea0e3c_key -iv $encrypted_7ab094ea0e3c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-226823
  - gcloud config set compute/zone us-central1-a	
  - gcloud container clusters get-credentials  k8s-multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t 469996/doc-k8s-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 469996/doc-k8s-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master